
export const SET_STATION_LIST = 'SET_STATION_LIST'
export const LOAD_STATION_LIST = 'LOAD_STATION_LIST'

export const SET_ITEM_LIST = 'SET_ITEM_LIST'
export const LOAD_ITEM_LIST = 'LOAD_ITEM_LIST'

export const LOAD_SAVED_DATA = 'LOAD_SAVED_DATA'

export const TOGGLE_SAVE_SELECTION = 'TOGGLE_SAVE_SELECTION'
export const TOGGLE_AUTO_RETRIEVE = 'TOGGLE_AUTO_RETRIEVE'
